### ISSUE TITLE
Reason Redux lite

### ISSUE THREAD

**Issue by steida** [reasonml-community/reductive#13]
I understand why we might not need Redux in Reason, still, I have some questions.

Without Redux, app state is in the top component, which is actually composition root. 
We can pass props and we can also share props across components.
But, isn't data a side effect, which naturally belongs to React context?
I believe we still need context actions dispatcher because it initiates side effect change.
Maybe, this should be defined by React API itself, then, we would have common API for side effects.
Thoughts?

**Comment by rickyvetter** [comment]
I think it makes sense for the dispatcher to be passed as a prop over context because it is more explicit in intent and easier to trace callsites. Why do you think context makes sense for dispatching? One problem I see is you could theoretically be dispatching at multiple levels of your app - say you have AppB which consumes and renders AppA - how would AppA components know where to dispatch?

React API providing a way to deal with dispatching/side effects would be ideal. @jordwalke and @cristianoc have done some experimentation around this concept, but nothing concrete.

**Comment by steida** [comment]
Prop is for components only, context affects whole app state.

**Comment by rickyvetter** [comment]
In practice there isn't any difference between whole app state and component state of your react root. I think that context isn't understood/supported well enough to be encouraged. If you're interested in this problem space, I'd love to see an implementation that works the way you expect to compare to something like reductive and plain react state management!

**Comment by steida** [comment]
Still, I think context pro app "constants" makes sense. For example: i18n, themes, router, etc.

**Comment by rickyvetter** [comment]
I think there might be some valid use cases for context, definitely. But the API is unstable and has unexpected complexities when implemented for non-constants.

I would recommend following https://github.com/reasonml/reason-react/issues/25. Once context is supported in reason-react and we know more about a stable API, we can talk about how it would make sense to work with this in reductive.

Closing this for now since it's dependent on work with no concrete timeline.

**Comment by aappddeevv** [comment]
You could allow the self record passed to the lifecycle methods to be extensible by component authors and create a mkSelf type method to allow it to be created. That way you could add anything you want to self and make it available in your component. This would require a change in the reasonreact but can be API neutral. It would make the api for people who want to change it for a specific component harder of course :-) It's also probably a good escape hatch that is consistent with how the self is created already. I've done this for a scala.js version of reasonreact to pull in the context for exactly this reason.
