### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by bstro** [reasonml-community/reductive#25]
I haven't heard anyone discuss anything related to the use of `connect` with regards to reducer components in ReasonML. Does such a thing even make sense within the context of reasonml? The way `connect` reduces coupling between state and component hierarchies is very desirable to me. Is there a way to achieve the same thing?

**Comment by quicksnap** [comment]
Since static typing is much more robust in Reason, it is generally frowned upon to use a shortcut such as `connect`. Creating a prop that is passed down through the entire tree of your app is likely a better solution.

Would love to hear other opinions.

**Comment by quicksnap** [comment]
Damn.. I deleted my previous comment because I thought I was mixed up.. but I'll try again:

Since static typing in Reason is much more robust than Javascript, using a "shortcut" such as `connect` is generally frowned upon. It's much clearer simply to pass down a prop through your component tree and leverage the type system.

You can also pass down a "bag" of your state, dispatch, actions, etc. 

Optimizing this pattern to reduce unnecessary re-renders may be worth exploring. Would love to hear opinions of anyone else.

**Comment by bstro** [comment]
Doesn't this introduce coupling between state/paths to data in state and your component tree? i.e. coupling two hierarchies together.

**Comment by conartist6** [comment]
I'm confused. There is an analog of connect; it's `Provider.createMake`. Am I wrong?

**Comment by bstro** [comment]
Looks like you're right and I missed it :) Thanks!

**Comment by conartist6** [comment]
Great! I personally still think that the only way to describe solid patterning involves using createMake. See #26 for my reasoning. That language features make it convenient in the most simplistic situations not to use a container component seems irrelevant to me.
