### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by nlfiedler** [reasonml-community/reductive#36]
If not, I would be more than happy to take on that responsibility. I love ReasonML and this project and I want to see it thrive. Application state management is an important aspect of the projects I work on, so having a well maintained library is crucial for me.

At the very least, please comment on my pull requests.

**Comment by melbourne2991** [comment]
Damn it, just spent the last couple of hours trying to figure that curry error out - the one mentioned in one of your PRs (assuming it was something I had done due to this all being new territory for me).

@nlfiedler It might be worth just forking it at this point as it seems as though the original maintainers may have gone awol.

**Comment by nlfiedler** [comment]
@wyze Do you have any suggestions for how to move forward with this project? You're in the reasonml-community, and have contributed to this repo in the past, so I'm hoping you know how to respond to questions about the maintenance of this project.

**Comment by wyze** [comment]
Hey Nathan,

Sorry for the delayed response. According to the readme in https://github.com/reasonml-community/meta it should be maintained by @rickyvetter. Looks like I do have permissions to merge PRs so I can take a look at them.

In the meantime, we can see if we can summon @glennsl and see about getting you added to the maintainers of this project.

**Comment by quicksnap** [comment]
I do monitor some of these threads, but I'm very removed from ReasonML so I can't add much. I lack the permissions to add someone else.

**Comment by glennsl** [comment]
@nlfiedler Could you try to get hold of @rickyvetter on Discord? Or alternatively @chenglou, who should be able to reach Ricky IRL.

I don't want to go over their heads, especially since I'm not much involved in the community these days. But if all else fails, I think we can assign a new maintainer if three org members support it.

**Comment by rickyvetter** [comment]
Hey folks! Apologies for being missing for a while here. I'm working mostly on some FB internal projects and have been somewhat ignoring open source stuff. This is my bad. Looking at the PRs first right now and then I'll look at the open issues.

If someone else is interested in helping/taking over maintenance, please reach out!

**Comment by rickyvetter** [comment]
Closing this since things seem to be - at least for now - back on track. Thanks for the wakeup call. Please reach out to me any time about this repo if things aren't moving the direction you want. I am terrible at responding on github, but working to get better! And I am actually pretty good on all other mediums :)
